In [2]:
import torch

In [3]:
print(torch.__version__)

1.12.1+cpu


In [4]:
torch.cuda.is_available()

False

# INPLACE in torch

Now we will see how inplace is working with pytorch. In torch every function including _ sign is called inplace. That means which method includes _ that will automatically inplace change the data.

In [5]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add(x)
print(y)
# Nothing is change is y though we use add function

tensor([[0.0209, 0.4600],
        [0.6582, 0.9792]])
tensor([[0.6798, 0.7439],
        [0.2968, 0.0266]])
tensor([[0.6798, 0.7439],
        [0.2968, 0.0266]])


In [6]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x)
print(y)
# Now the y value has been chnaged because of the use of _ in add function

tensor([[0.1761, 0.1462],
        [0.7231, 0.7963]])
tensor([[0.0942, 0.2115],
        [0.7488, 0.7456]])
tensor([[0.2703, 0.3577],
        [1.4719, 1.5420]])


In [29]:
x = torch.rand(20, 4)

In [24]:
# by view method we can reshape the tensor
y = x.view(8,10)
y

tensor([[0.2508, 0.7177, 0.4729, 0.9998, 0.2351, 0.5311, 0.4892, 0.9369, 0.1601,
         0.0302],
        [0.6953, 0.1933, 0.4774, 0.5180, 0.8383, 0.2343, 0.0473, 0.3708, 0.3686,
         0.6448],
        [0.5051, 0.7330, 0.3987, 0.2080, 0.7144, 0.8180, 0.5949, 0.3977, 0.0297,
         0.0683],
        [0.6894, 0.9000, 0.3311, 0.7288, 0.8335, 0.4464, 0.0160, 0.2104, 0.3381,
         0.7808],
        [0.2540, 0.4424, 0.4848, 0.7006, 0.7503, 0.8523, 0.2216, 0.7004, 0.6249,
         0.9133],
        [0.9940, 0.5734, 0.5067, 0.6739, 0.7280, 0.4338, 0.6610, 0.3848, 0.3742,
         0.5540],
        [0.1606, 0.7045, 0.5594, 0.1416, 0.8969, 0.2236, 0.4677, 0.5568, 0.3781,
         0.2348],
        [0.5890, 0.6323, 0.1993, 0.0230, 0.5876, 0.5704, 0.5263, 0.7799, 0.2215,
         0.9863]])

In [28]:
# by view method we can reshape the tensor
# In the view method if we specify the first value to -1 it will
# automatically correctly determine the size and reshape the tensor 
y = x.view(-1,2)
print(y.size())

torch.Size([40, 2])


In [26]:
y.size()

torch.Size([40, 2])