In [22]:
import torch

In [23]:
print(torch.__version__)

1.12.1+cpu


In [24]:
torch.cuda.is_available()

False

In [25]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [26]:
# converting a list to tensor 
li = [1,2,3,4,5,6,7,8]
li_matrix = torch.tensor(li)
print(li_matrix)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


# Access tensor value

In [27]:
all_zero = torch.zeros(3)
print(all_zero)
print(all_zero.type(torch.int32))
print(all_zero[1])
print(all_zero[1].numpy())

tensor([0., 0., 0.])
tensor([0, 0, 0], dtype=torch.int32)
tensor(0.)
0.0


### Getting information from tensors (tensor attributes)

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules),can use tensor.shape
    dtype - what datatype are the elements within the tensor stored in?,can use tensor.dtype
    device - what device is the tensor stored on? (usually GPU or CPU),can use tensor.device
Let's create a random tensor and find out details about it.

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0446, 0.2809, 0.6971, 0.0784],
        [0.3314, 0.9111, 0.8628, 0.9611],
        [0.3417, 0.9500, 0.7479, 0.4085]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Getting information from tensors (tensor methods)

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules),can use tensor.size()
    dtype - what datatype are the elements within the tensor stored in?,can use tensor.type()
Let's create a random tensor and find out details about it.

In [29]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Datatype of tensor: {some_tensor.type()}")

tensor([[0.0715, 0.1328, 0.1058, 0.6253],
        [0.1112, 0.7226, 0.0067, 0.3252],
        [0.8802, 0.1213, 0.5218, 0.1853]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.FloatTensor


# Creating a range of tensors and tensors like

In [30]:
one_to_ten = torch.arange(start=1,end=50,step=5)
one_to_ten

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [31]:
####### torch.zeros_like() is use to convert a tensor to zero value
final_zero = torch.zeros_like(one_to_ten)
final_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# INPLACE in torch

Now we will see how inplace is working with pytorch. In torch every function including _ sign is called inplace. That means which method includes _ that will automatically inplace change the data.

In [32]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add(x)
print(y)
# Nothing is change is y though we use add function

tensor([[0.1417, 0.6439],
        [0.9026, 0.9227]])
tensor([[0.4395, 0.8537],
        [0.9017, 0.4099]])
tensor([[0.4395, 0.8537],
        [0.9017, 0.4099]])


In [33]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x)
print(y)
# Now the y value has been chnaged because of the use of _ in add function

tensor([[0.9895, 0.4594],
        [0.9617, 0.3663]])
tensor([[0.2810, 0.3472],
        [0.1974, 0.8518]])
tensor([[1.2704, 0.8067],
        [1.1590, 1.2181]])


## Matrix multiplication

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

    The inner dimensions must match:
        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
    The resulting matrix has the shape of the outer dimensions:
        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

In [38]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [39]:
# Element-wise matrix mutlication
tensor * tensor

tensor([1, 4, 9])

In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

The in-built torch.matmul() method is faster.

In [41]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 2.51 ms


tensor(14)

In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [43]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

    torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
    tensor.T - where tensor is the desired tensor to transpose.

In [45]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [46]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [47]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


# Reshape

In [34]:
x = torch.rand(20, 4)

In [35]:
# by view method we can reshape the tensor
y = x.view(8,10)
y

tensor([[0.1904, 0.3770, 0.7847, 0.6678, 0.5433, 0.2040, 0.9204, 0.8815, 0.4165,
         0.7954],
        [0.0087, 0.8497, 0.8111, 0.9324, 0.2730, 0.2476, 0.1776, 0.6243, 0.2951,
         0.0608],
        [0.8186, 0.2060, 0.2017, 0.0459, 0.0687, 0.0055, 0.2212, 0.3716, 0.4205,
         0.2785],
        [0.0421, 0.4335, 0.9212, 0.2393, 0.8943, 0.9645, 0.5945, 0.6593, 0.3437,
         0.1250],
        [0.6483, 0.5046, 0.5564, 0.0750, 0.9682, 0.7734, 0.0974, 0.8603, 0.9853,
         0.9340],
        [0.4061, 0.0443, 0.9581, 0.8404, 0.8630, 0.2284, 0.9667, 0.2119, 0.5488,
         0.3938],
        [0.9891, 0.8372, 0.5219, 0.7277, 0.9733, 0.5599, 0.8539, 0.0455, 0.8744,
         0.9464],
        [0.7883, 0.0360, 0.2621, 0.5139, 0.1011, 0.7739, 0.0310, 0.2288, 0.5706,
         0.8828]])

In [36]:
# by view method we can reshape the tensor
# In the view method if we specify the first value to -1 it will
# automatically correctly determine the size and reshape the tensor 
y = x.view(-1,2)
print(y.size())

torch.Size([40, 2])


In [37]:
y.size()

torch.Size([40, 2])

###  Finding the min, max, mean, sum, etc (aggregation)

In [52]:
x = torch.arange(0, 101, 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [66]:
x.min(),x.max(),x.sum()

(tensor(0), tensor(100), tensor(550))

In [60]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

To find the mean value of a tensor it has to be float data type

y = torch.arange(0, 101, 10)
print(y)
y = y.type(torch.float32)
print(y)
print(y.mean())

#### Finding the positional min and max

In [70]:
x = torch.arange(0,100,10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [73]:
## Find the position or index in tensor that has minimum and maximum value 
x.argmin(),x.argmax()

(tensor(0), tensor(9))